# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-22 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productDetails', '0002_productsuggestions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='rack_No',
            field=models.CharField(max_length=100),
        ),
    ]
